[project]
name = "magnusia"
version = "0.1.0"
description = "PrÃ©diction de gagnant de parties d'echecs"
readme = "README.md"
requires-python = ">=3.13"

dependencies = [
    "pytest",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
