site_name: Magnus IA Doc
site_description: Documentation pour Magnus IA

nav:
  - Accueil: index.md
  - Guide d'installation: install.md
  - DÃ©marrage Rapide (Quick Start): quick_start.md
  - Notebook: notebook.md
